jobs:

  include:
    - stage: test_backend
      language: java
      sudo: false
      script: 
        - cd BACKEND
        - mvn test -B
    
    - stage: build_frontend
      name: "Frontend build"
      language: node_js
      node_js:
        - '8.0'
      before_script:
        - npm install
        - npm install -g @angular/cli
        - npm install -g @compodoc/compodoc
      script:
        - cd FRONTEND
        - npm run compodoc
      
      

stages:
  - build_frontend
