language: java

sudo: false

jobs:

  include:
    - stage: test_backend
      script: cd BACKEND
      script: mvn clean test
    - stage: compile
      script: mvn clean compile

stages:
  - compile
  - test_backend
