jobs:

  include:
    # - stage: test_backend
    #   name: "Testing backend"
    #   language: java
    #   sudo: false
    #   script: 
    #     - cd module-backend
    #     - mvn test
      
#     - stage: build_frontend
#       name: "Building Angular"
#       language: node_js
#       node_js:
#         - '10.15.3'
#       install:
#         - cd module-frontend
#         - npm install
# #        - npm audit fix --force
#       script:
#         - npm run build
     
    - stage: generate_frontend_docs
      name: "Generating documents with Compodoc"
      language: node_js
      node_js:
        - '10.15.3'
      install:
        - cd module-frontend
        - npm install
#        - npm audit fix --force
      script:
        - npm run compodoc
        - bash ./deploy.sh
       
    - stage: sonarcloud
      name: "Running SonarCloud"
      language: java
      sudo: false
      script: 
        - cd module-backend
        - mvn clean package sonar:sonar -Dsonar.projectKey=DorogiB_ProjEszk19 -Dsonar.organization=dorogib-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9df464cadf54111d1831bb94fe45d6dcc0744418
    
env:
  global:
    - GITHUB_REF: github.com/DorogiB/ProjEszk19.git

stages:
  # - test_backend
  # - build_frontend
  - generate_frontend_docs
  - sonarcloud
