language: java

sudo: false

jobs:

  include:
    - stage: test_backend
      script: cd BACKEND
      script: mvn clean test
    - stage: compile_backend
      script: cd BACKEND
      script: mvn clean compile

stages:
  - compile_backend
  - test_backend
